# Server configuration
server:
  port: 8181


# Spring framework configuration
spring:
  cloud:
    # Disable configuration server request to work provided values
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/spring6
    username: spring6
    # Using environment variable ENCRYPT_KEY=ENCRYPT_KEY
    # Getting the value with POST localhost:8888/encrypt and the password in its body (using config-server)
    # Raw password: spring6
    password: "{cipher}c8e1f3a8e0f5d7246a0dcbe620b97de51b580a1ef16f80ffafd3989920287278"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


# Security configuration
security:
  # JWT configuration
  jwk:
    id: 'local-f57f-46a2-b502-8a24c308be7f'
    public: classpath:/jwt/app.pub
    private: classpath:/jwt/app.key


# Encryption configuration
encrypt:
  # Defined symmetric (shared) key to encrypt/decrypt text:
  #
  #  1. Receiving encrypted property values from Config Server like:
  #       spring.datasource.password: "{cipher}..."
  #
  #  2. Receiving encrypted column values from database like:
  #       security.application_client_details.signature_secret = '{cipher}...'
  #
  # To encrypt a text, use the endpoint POST: localhost:8888/encrypt and the text in its body
  key: ${ENCRYPT_KEY:ENCRYPT_KEY}


# Disable eureka server connection request
eureka:
  client:
    enabled: false


# Internal caches used by the microservice
cache:
  # To manage the configuration of the applications included in the microservice
  registeredClient:
    entryCapacity: 2
    expireInSeconds: 3600
    name: registeredClientCache


# Configure the logs
logging:
  level:
    org:
      springframework:
        # Set the level of the Spring Security package for debugging purpose
        security: trace


# Main properties in Spring Boot to configure some general purpose services
management:
  endpoints:
    web:
      exposure:
        # Actuator endpoints exposed: actuator/routes
        include: health, info
  tracing:
    sampling:
      # To log traceId and spanId in every request
      probability: 1.0


# API documentation
# In local the URLs are:
#   1. http://localhost:8181/security/oauth/api-docs to get the information in JSON format
#   2. http://localhost:8181/security/oauth/swagger-ui/index.html to display the UI with all defined endpoints
springdoc:
  api-docs:
    # Path of the OpenAPI documentation in JSON format
    path: /security/oauth/api-docs
  documentation:
    apiVersion: 1.0
    title: Security Oauth Rest Api
    description: Services related with authentication/authorization functionality
  # Custom properties to define security configuration for documented API
  security:
    authorization: Basic Auth
    schema: basic
  show-oauth2-endpoints: true
  swagger-ui:
    # To disable the swagger-ui default petstore url
    disable-swagger-default-url: true
    # Custom path of the swagger-ui HTML documentation
    path: /security/oauth/swagger-ui.html