# Server configuration
server:
  port: 8181


# Spring framework configuration
spring:
  config:
    import: configserver:http://localhost:8888


# Encryption configuration
encrypt:
  # Defined symmetric (shared) key to encrypt/decrypt text:
  #
  #  1. Receiving encrypted property values from Config Server like:
  #       spring.datasource.password: "{cipher}..."
  #
  #  2. Receiving encrypted column values from database like:
  #       security.application_client_details.signature_secret = '{cipher}...'
  #
  # To encrypt a text, use the endpoint POST: localhost:8888/encrypt and the text in its body
  key: ${ENCRYPT_KEY:ENCRYPT_KEY}