# Spring framework configuration
spring:
  application:
    name: config-server
  cloud:
    config:
      # Same value than git.defaultLabel
      label: main
      server:
        encrypt:
          # We will send encrypted properties
          enabled: false
        git:
          uri: https://github.com/doctore/Spring6Microservices_ConfigServerData.git
          searchPaths: gateway-server,security-custom-service,security-oauth-service
          defaultLabel: main


# Required to expose the routes included actuator: actuator/routes
management:
  endpoints:
    web:
      exposure:
        include: health, info