# Server configuration
server:
  port: 8180


# Spring framework configuration
spring:
  config:
    import: configserver:http://localhost:8888


# Defined symmetric (shared) key to encrypt/decrypt text.
# To encrypt a text, use the endpoint POST: localhost:8888/encrypt and the text in its body
encrypt:
  key: ${ENCRYPT_KEY:ENCRYPT_KEY}