# Server configuration
server:
  port: 8180

# Spring framework configuration
spring:
  # TODO: TEMPORAL BY NOW
  cloud:
    # Disable configuration server for testing
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/spring6
    username: spring6
    # Using environment variable ENCRYPT_KEY=ENCRYPT_KEY
    # Getting the value with POST localhost:8888/encrypt and the password in its body (using config-server)
    # Raw password: spring6
    #password: "{cipher}c8e1f3a8e0f5d7246a0dcbe620b97de51b580a1ef16f80ffafd3989920287278"
    password: spring6
  #jpa:
  #  properties:
  #    hibernate:
  #      dialect: org.hibernate.dialect.PostgreSQLDialect    # No longer required (selected by default)

  # To include trace and span identifiers in every log
  #sleuth:
  #  reactor:
  #    instrumentation-type: decorate_on_each

# Internal caches used by the microservice
cache:
  applicationClientDetails:
    entryCapacity: 2
    expireInSeconds: 3600
    name: applicationClientDetailsCache